"""Matchstick Equation game logic for Pop Pop's Games.

The equation is drawn from digit slots (standard 7-segment digits) and a
single +/- operator slot (2 segments); the "=" sign is fixed scaffolding and
never touched. A puzzle is generated by building a true equation, then
"corrupting" it by moving exactly one stick from a lit segment to an unlit
one elsewhere — both the source and destination slots must still land on a
recognizable digit/operator, and the resulting equation must be false. That
guarantees a puzzle is always solvable in exactly one move (undo the
corruption), without needing any hand-authored puzzle data.

During play, moves are free-form: any lit segment can be moved to any unlit
segment anywhere in the equation. There's no validity gate on play moves —
if a move produces an unrecognized shape, the equation just isn't true yet.

"Solve One For Me" is a separate, stateless utility: given an arbitrary
equation the player types in, find the minimum number of stick-moves that
makes it true (not assumed to be 1) by searching every same-shape equation
reachable with the exact same total stick count.
"""

import random
import re

DIGIT_SEGMENTS = {
    "0": frozenset("abcdef"),
    "1": frozenset("bc"),
    "2": frozenset("abdeg"),
    "3": frozenset("abcdg"),
    "4": frozenset("bcfg"),
    "5": frozenset("acdfg"),
    "6": frozenset("acdefg"),
    "7": frozenset("abc"),
    "8": frozenset("abcdefg"),
    "9": frozenset("abcdfg"),
}
OPERATOR_SEGMENTS = {
    "+": frozenset("hv"),
    "-": frozenset("h"),
}
ALL_SEGMENTS_BY_KIND = {
    "digit": "abcdefg",
    "operator": "hv",
}
DIGIT_STICK_COUNT = {d: len(segs) for d, segs in DIGIT_SEGMENTS.items()}

LEVELS = ["easy", "medium", "hard"]
DEFAULT_LEVEL = "easy"
LEVEL_POINTS = {"easy": 1, "medium": 2, "hard": 3}

OPERAND_RANGES = {
    "easy":   ((1, 9), (1, 9)),
    "medium": ((10, 99), (1, 9)),
    "hard":   ((10, 99), (10, 99)),
}

MAX_CUSTOM_DIGITS = 3  # cap per number so the "Solve One For Me" search stays fast
_EQUATION_RE = re.compile(r"^\s*(\d+)\s*([+-])\s*(\d+)\s*=\s*(\d+)\s*$")


def _digit_slots(digits):
    """digits: a string like '16' or '03' — each character becomes one digit
    slot, preserving length/leading zeros exactly as given."""
    return [{"kind": "digit", "segments": set(DIGIT_SEGMENTS[ch])} for ch in digits]


def _build_slots_from_parts(a_str, op, b_str, result_str):
    slots = []
    slots += _digit_slots(a_str)
    slots.append({"kind": "operator", "segments": set(OPERATOR_SEGMENTS[op])})
    slots += _digit_slots(b_str)
    slots.append({"kind": "equals"})
    slots += _digit_slots(result_str)
    return slots


def _build_slots(a, op, b, result):
    return _build_slots_from_parts(str(a), op, str(b), str(result))


def _valid_pattern(kind, segset):
    if kind == "digit":
        return frozenset(segset) in DIGIT_SEGMENTS.values()
    if kind == "operator":
        return frozenset(segset) in OPERATOR_SEGMENTS.values()
    return True


def _decode_slot(slot):
    if slot["kind"] == "equals":
        return "="
    table = DIGIT_SEGMENTS if slot["kind"] == "digit" else OPERATOR_SEGMENTS
    segs = frozenset(slot["segments"])
    for ch, pattern in table.items():
        if pattern == segs:
            return ch
    return None


def _evaluate(expr):
    for op, fn in (("+", lambda x, y: x + y), ("-", lambda x, y: x - y)):
        if op in expr:
            left, right = expr.split(op, 1)
            if left.isdigit() and right.isdigit():
                return fn(int(left), int(right))
    return None


def _equation_true(slots):
    chars = [_decode_slot(s) for s in slots]
    if any(c is None for c in chars):
        return False
    text = "".join(chars)
    if text.count("=") != 1:
        return False
    left, right = text.split("=")
    if not right.isdigit():
        return False
    value = _evaluate(left)
    return value is not None and value == int(right)


def _moveable_positions(slots):
    positions = []
    for i, slot in enumerate(slots):
        segs = ALL_SEGMENTS_BY_KIND.get(slot["kind"])
        if segs:
            positions += [(i, seg) for seg in segs]
    return positions


def _segment_set(slots):
    """Every currently-lit moveable (index, seg) position, as a flat set."""
    out = set()
    for i, s in enumerate(slots):
        if s["kind"] in ("digit", "operator"):
            out.update((i, seg) for seg in s["segments"])
    return out


def _copy_slots(slots):
    """Independent deep-enough copy: each slot's segments set is its own object,
    so mutating one copy (e.g. during play) never leaks into another (e.g. the
    frozen original kept for "Show Me")."""
    copies = []
    for s in slots:
        c = {"kind": s["kind"]}
        if "segments" in s:
            c["segments"] = set(s["segments"])
        copies.append(c)
    return copies


def _try_corrupt(slots):
    """Move one stick from a lit position to an unlit one, keeping both ends
    on recognizable digits/operators, so the equation becomes false. Returns
    (corrupted_slots, solution_moves) where solution_moves is a one-move list
    [(from_index, from_seg, to_index, to_seg)] that undoes the corruption —
    or (None, None) if no such move exists for this equation."""
    positions = _moveable_positions(slots)
    lit = [(i, seg) for (i, seg) in positions if seg in slots[i]["segments"]]
    unlit = [(i, seg) for (i, seg) in positions if seg not in slots[i]["segments"]]
    random.shuffle(lit)
    random.shuffle(unlit)

    for si, sseg in lit:
        for di, dseg in unlit:
            if si == di and sseg == dseg:
                continue
            trial = _copy_slots(slots)
            trial[si]["segments"].discard(sseg)
            trial[di]["segments"].add(dseg)
            if not _valid_pattern(trial[si]["kind"], trial[si]["segments"]):
                continue
            if not _valid_pattern(trial[di]["kind"], trial[di]["segments"]):
                continue
            if not _equation_true(trial):
                # Corruption moved a stick FROM (si,sseg) TO (di,dseg); the fix
                # is the reverse: pick up FROM (di,dseg), place AT (si,sseg).
                return trial, [(di, dseg, si, sseg)]
    return None, None


def _random_equation(level):
    (lo1, hi1), (lo2, hi2) = OPERAND_RANGES.get(level, OPERAND_RANGES[DEFAULT_LEVEL])
    op = random.choice(["+", "-"])
    a = random.randint(lo1, hi1)
    b = random.randint(lo2, hi2)
    if op == "-":
        a, b = max(a, b), min(a, b)
        result = a - b
    else:
        result = a + b
    return a, op, b, result


def _generate_puzzle(level, max_tries=200):
    for _ in range(max_tries):
        a, op, b, result = _random_equation(level)
        true_slots = _build_slots(a, op, b, result)
        corrupted, solution = _try_corrupt(true_slots)
        if corrupted is not None:
            return corrupted, solution
    # Extremely unlikely fallback: a fixed equation known to always corrupt cleanly.
    return _try_corrupt(_build_slots(7, "+", 1, 8))


def _generate_two_move_puzzle(level, max_tries=50):
    """Hard-mode variant: corrupt a true equation twice in a row, then verify
    with an exhaustive search that the result *actually* needs 2 moves — two
    independent random corruptions can coincidentally land only 1 move away
    from some other same-shape true equation, so the minimum can't just be
    assumed from the construction. Returns (None, None) if no verified
    2-move puzzle turns up within max_tries (caller falls back to 1-move)."""
    for _ in range(max_tries):
        a, op, b, result = _random_equation(level)
        true_slots = _build_slots(a, op, b, result)
        once, _undo1 = _try_corrupt(true_slots)
        if once is None:
            continue
        twice, _undo2 = _try_corrupt(once)
        if twice is None:
            continue

        d1, d2, d3 = len(str(a)), len(str(b)), len(str(result))
        lit = _segment_set(twice)
        best_moves, best_extra, best_missing = _exhaustive_min_reshuffle(lit, len(lit), d1, d2, d3)
        if best_moves == 2:
            return twice, _moves_from_reshuffle(best_extra, best_missing)
    return None, None


def new_game(level=DEFAULT_LEVEL):
    if level not in LEVELS:
        level = DEFAULT_LEVEL
    slots = solution = None
    if level == "hard" and random.random() < 0.5:
        slots, solution = _generate_two_move_puzzle(level)
    if slots is None:
        slots, solution = _generate_puzzle(level)
    return {
        "slots": slots,
        "original_slots": _copy_slots(slots),
        "solution": solution,  # [(from_index, from_seg, to_index, to_seg), ...]
        "level": level,
        "par_moves": len(solution),
        "moves_used": 0,
        "over": False,
        "won": False,
        "gave_up": False,
        "scored": False,
    }


def reset_puzzle(game):
    """Restore the current puzzle to its original (unsolved) state — same
    equation, moves_used back to 0. Unlike new_game(), this doesn't generate
    a different puzzle. `scored` is left untouched: a puzzle already scored
    once doesn't get re-scored just for being replayed after a reset."""
    game["slots"] = _copy_slots(game["original_slots"])
    game["moves_used"] = 0
    game["over"] = False
    game["won"] = False
    game["gave_up"] = False


def give_up(game):
    """Concede: reveal the original puzzle and its solution immediately.
    Sets `over=True` (won=False) right away so this counts as a loss for
    scoring — see ms_apply_score's `gave_up` check — even if the player
    goes on to replay the shown moves by hand afterward. `scored` sticks
    once set, so that replay can't earn a second, un-conceded score."""
    game["slots"] = _copy_slots(game["original_slots"])
    game["moves_used"] = 0
    game["over"] = True
    game["won"] = False
    game["gave_up"] = True


def move_stick(game, from_index, from_seg, to_index, to_seg):
    if game["over"]:
        return
    slots = game["slots"]
    if not (0 <= from_index < len(slots)) or not (0 <= to_index < len(slots)):
        return
    src, dst = slots[from_index], slots[to_index]
    if src["kind"] not in ("digit", "operator") or dst["kind"] not in ("digit", "operator"):
        return
    if from_seg not in ALL_SEGMENTS_BY_KIND[src["kind"]] or to_seg not in ALL_SEGMENTS_BY_KIND[dst["kind"]]:
        return
    if from_seg not in src["segments"]:
        return
    if from_index == to_index and from_seg == to_seg:
        return
    if to_seg in dst["segments"]:
        return

    src["segments"].discard(from_seg)
    dst["segments"].add(to_seg)
    game["moves_used"] += 1

    if _equation_true(slots):
        game["over"] = True
        game["won"] = True


def serialize_slots(slots):
    return [
        {"kind": s["kind"], "segments": sorted(s.get("segments", ()))}
        for s in slots
    ]


def game_state(game):
    over = game["over"]
    return {
        "slots": serialize_slots(game["slots"]),
        "moves_used": game["moves_used"],
        "par_moves": game["par_moves"],
        "over": over,
        "won": game["won"],
        "gave_up": game["gave_up"],
        "level": game["level"],
        "levels": LEVELS,
        "original_slots": serialize_slots(game["original_slots"]) if over else None,
        "solution": [
            {"from_index": fi, "from_seg": fs, "to_index": ti, "to_seg": ts}
            for (fi, fs, ti, ts) in game["solution"]
        ] if over else None,
    }


# ---------------------------------------------------------------------------
# "Solve One For Me" — stateless minimum-moves solver for a user-typed equation
# ---------------------------------------------------------------------------

def _digits_stick_count(digits_str):
    return sum(DIGIT_STICK_COUNT[ch] for ch in digits_str)


def parse_custom_equation(text):
    """Parse a user-typed equation like '3 - 3 = 1'. Returns (a_str, op, b_str,
    result_str) with leading zeros preserved, or raises ValueError with a
    user-facing message."""
    if not text or len(text) > 40:
        raise ValueError("Please enter an equation like: 3 - 3 = 1")
    match = _EQUATION_RE.match(text)
    if not match:
        raise ValueError("Please enter an equation like: 3 - 3 = 1 (just digits, + or -, and =)")
    a_str, op, b_str, result_str = match.groups()
    if max(len(a_str), len(b_str), len(result_str)) > MAX_CUSTOM_DIGITS:
        raise ValueError(f"Please keep each number to {MAX_CUSTOM_DIGITS} digits or fewer.")
    return a_str, op, b_str, result_str


def _exhaustive_min_reshuffle(lit, budget, d1, d2, d3):
    """Search every d1/d2/d3-digit equation reachable with the exact same
    total stick budget as `lit` (a set of currently-lit (index, seg) pairs),
    and return (best_moves, best_extra, best_missing) for the closest one —
    `best_extra` are lit positions that must be vacated, `best_missing` are
    unlit positions that must be filled, len(best_extra) == len(best_moves)
    since the budget is conserved. Returns (None, None, None) if no equation
    of that shape matches the budget at all."""
    best_moves = None
    best_extra = best_missing = None

    for cand_op in ("+", "-"):
        op_cost = len(OPERATOR_SEGMENTS[cand_op])
        for a in range(10 ** d1):
            a_c = str(a).zfill(d1)
            a_cost = _digits_stick_count(a_c)
            for b in range(10 ** d2):
                value = a + b if cand_op == "+" else a - b
                if value < 0 or value >= 10 ** d3:
                    continue
                b_c = str(b).zfill(d2)
                result_c = str(value).zfill(d3)
                total_cost = a_cost + op_cost + _digits_stick_count(b_c) + _digits_stick_count(result_c)
                if total_cost != budget:
                    continue
                cand_slots = _build_slots_from_parts(a_c, cand_op, b_c, result_c)
                cand_lit = _segment_set(cand_slots)
                extra = lit - cand_lit
                missing = cand_lit - lit
                moves_needed = len(extra)
                if best_moves is None or moves_needed < best_moves:
                    best_moves = moves_needed
                    best_extra, best_missing = extra, missing
                    if best_moves == 0:
                        break
            if best_moves == 0:
                break
        if best_moves == 0:
            break

    return best_moves, best_extra, best_missing


def _moves_from_reshuffle(extra, missing):
    return [
        (fi, fs, ti, ts)
        for (fi, fs), (ti, ts) in zip(sorted(extra), sorted(missing))
    ]


def solve_custom_equation(text):
    """Find the fewest stick-moves to make a user-typed equation true, trying
    both +/- as the operator and every same-length digit combination that
    keeps the exact same total stick count (the only thing moves preserve).
    Returns (original_slots, solution_moves, moves_needed), or None if no
    equation of the same shape is reachable with that exact stick budget.
    Raises ValueError for malformed input (from parse_custom_equation)."""
    a_str, op, b_str, result_str = parse_custom_equation(text)
    original_slots = _build_slots_from_parts(a_str, op, b_str, result_str)
    original_lit = _segment_set(original_slots)
    budget = len(original_lit)
    d1, d2, d3 = len(a_str), len(b_str), len(result_str)

    best_moves, best_extra, best_missing = _exhaustive_min_reshuffle(original_lit, budget, d1, d2, d3)
    if best_moves is None:
        return None
    return original_slots, _moves_from_reshuffle(best_extra, best_missing), best_moves
